"""init-db

Revision ID: 9e608452170a
Revises: c006e8463eb4
Create Date: 2024-05-24 17:52:35.706656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e608452170a'
down_revision = 'c006e8463eb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
